### ISSUE TITLE
Code changes required when upgrading from 5.3x to 5.6.x

### ISSUE THREAD

**Issue by kicsyromy** [dbus2/zbus#1371]
When upgrading from 5.3 to 5.6 for out project some minor code changed were required when using streams.

We were listening to SystemD's DBus API for changes, and subscribed to the UnitFilesChanged signal using streams.

The following code was compiling fine with 5.3.x:
```rust
use zbus::export::futures_util::StreamExt;
...
let systemd1 = SystemDManagerProxy::new(&bus)?;
if let subscribe_ok = if let Err(err) = systemd1.subscribe() {
    log::error!("Failed to subscribe to SystemD notifications, service refresh will be significantly more expensive: {err}");
    false
} else {
    tokio::spawn({
        let systemd1 = systemd1.clone();
        async move {
            let mut unit_files_changed = match systemd1.receive_unit_files_changed().await {
                Ok(unit_files_changed) => unit_files_changed,
                Err(e) => {
                    log::error!("Failed to receive unit files changed: {e}");
                    return;
                }
            };

            let mut reloading = match systemd1.receive_reloading().await {
                Ok(reloading) => reloading,
                Err(e) => {
                    log::error!("Failed to receive reloading: {e}");
                    return;
                }
            };

            loop {
                tokio::select! {
                    _ = unit_files_changed.next() => {
                        full_refresh_required.store(true, Ordering::Release);
                    }
                    _ = reloading.next() => {
                        full_refresh_required.store(true, Ordering::Release);
                    }
                }
            }
        }
    });

    true
};
```

But fails to compile with 5.6.x. In order to fix it the `use` statement needs to be replaced with `use zbus::export::ordered_stream::OrderedStreamExt;`

Apologies if the change was intended, in which case feel free to close the issue.

Thanks!

**Comment by zeenix** [comment]
> When upgrading from 5.3 to 5.6 for out project some minor code changed were required when using streams.

Oh no. That's not intended at all.

Could you please share the error you got? I believe this is an unintentional breakage from https://github.com/dbus2/zbus/pull/1340

**Comment by solomoncyj** [comment]
https://copr.fedorainfracloud.org/coprs/solomoncyj/rust/build/9020784/

**Comment by kicsyromy** [comment]
```bash
error[E0599]: no method named `next` found for struct `UnitFilesChangedStream` in the current scope
   --> platform-linux/src/services/systemd/mod.rs:154:52
    |
154 |   ...                   _ = unit_files_changed.next() => {
    |                                                ^^^^
    |
   ::: platform-linux/src/services/systemd/systemd_manager.rs:23:1
    |
23  | / #[proxy(
24  | |     interface = "org.freedesktop.systemd1.Manager",
25  | |     default_service = "org.freedesktop.systemd1",
26  | |     default_path = "/org/freedesktop/systemd1"
27  | | )]
    | |__- method `next` not found for this struct
    |
    = help: items from traits can only be used if the trait is in scope
help: the following traits which provide `next` are implemented but not in scope; perhaps you want to import one of them
    |
21  + use fallible_iterator::FallibleIterator;
    |
21  + use fallible_streaming_iterator::FallibleStreamingIterator;
    |
21  + use futures_lite::stream::StreamExt;
    |
21  + use quote::__private::ext::RepToTokensExt;
    |
      and 3 other candidates
help: there is a method `try_next` with a similar name
    |
154 |                             _ = unit_files_changed.try_next() => {
    |                                                    ++++
```

**Comment by zeenix** [comment]
@solomoncyj @kicsyromy Thanks so much. I'll have a look either tonight or tomorrow. In the meantime, if anyone could provide me with a minimal reproducer, it'll be very helpful in resolving this quickly.

**Comment by solomoncyj** [comment]
> [@solomoncyj](https://github.com/solomoncyj) [@kicsyromy](https://github.com/kicsyromy) Thanks so much. I'll have a look either tonight or tomorrow. In the meantime, if anyone could provide me with a minimal reproducer, it'll be very helpful in resolving this quickly.

https://gitlab.com/mission-center-devs/gng/-/merge_requests/19 this pr should show whats happening

**Comment by refi64** [comment]
Don't have time to check atm, but did a quick look and I believe this is actually due to [this commit](https://github.com/dbus2/zbus/commit/63ce665420ebb59d91d5a64e8acb55fbe07d49b8). Based on doing a quick build of the `gng` repo locally w/ zbus 5.6, I think the report is missing these logs at the start:

```
error[E0432]: unresolved import `zbus::export::futures_util`
  --> platform-linux/src/services/systemd/mod.rs:26:19
   |
26 | use zbus::export::futures_util::StreamExt;
   |                   ^^^^^^^^^^^^ could not find `futures_util` in `export`
```

AIUI `zbus::export` is "internal" and only designed for zbus itself. The linked commit removed the `futures_util` dependency—which is fine, because that module is intended to be internal anyway—except `platform-linux` was importing it, and now `StreamExt` isn't available. You can fix it by depending on `futures-lite` or `futures-util` from the crate and then using `StreamEXt` from there.

**Comment by zeenix** [comment]
@refi64 Thanks so much for looking into this! 👍 

> AIUI `zbus::export` is "internal" and only designed for zbus itself.

Correct. There is a reason it's `#[doc(hidden)]` and there is [a comment above the module declaration](https://github.com/dbus2/zbus/blob/main/zbus/src/lib.rs#L97) saying so **very** explicitly:

> // Macro support module, not part of the public API.

So, sorry but if you still use this API, then you're asking for trouble. As @refi64 pointed out, there is a very simple fix for the problem.

**Comment by zeenix** [comment]
> > // Macro support module, not part of the public API.
> 
> So, sorry but if you still use this API, then you're asking for trouble. As [@refi64](https://github.com/refi64) pointed out, there is a very simple fix for the problem.

Still, I do appreciate you reporting this @kicsyromy and @solomoncyj. 🙏
